
window.exampleBirdData = [
    {
        "lng": -90.0365832,
        "locName": "Lake Pontchartrain--Seabrook",
        "howMany": 1,
        "sciName": "Hydroprogne caspia",
        "obsValid": true,
        "locationPrivate": false,
        "obsDt": "2017-06-22 12:04",
        "obsReviewed": false,
        "comName": "Caspian Tern",
        "lat": 30.0316211,
        "locID": "L727346"
    },
    {
        "lng": -90.0365832,
        "locName": "Lake Pontchartrain--Seabrook",
        "howMany": 35,
        "sciName": "Thalasseus maximus",
        "obsValid": true,
        "locationPrivate": false,
        "obsDt": "2017-06-22 12:04",
        "obsReviewed": false,
        "comName": "Royal Tern",
        "lat": 30.0316211,
        "locID": "L727346"
    },
    {
        "lng": -90.0365832,
        "locName": "Lake Pontchartrain--Seabrook",
        "howMany": 35,
        "sciName": "Columba livia",
        "obsValid": true,
        "locationPrivate": false,
        "obsDt": "2017-06-22 12:04",
        "obsReviewed": false,
        "comName": "Rock Pigeon",
        "lat": 30.0316211,
        "locID": "L727346"
    },
    {
        "lng": -90.0365832,
        "locName": "Lake Pontchartrain--Seabrook",
        "howMany": 3,
        "sciName": "Larus delawarensis",
        "obsValid": true,
        "locationPrivate": false,
        "obsDt": "2017-06-22 12:04",
        "obsReviewed": false,
        "comName": "Ring-billed Gull",
        "lat": 30.0316211,
        "locID": "L727346"
    },
    {
        "lng": -90.0365832,
        "locName": "Lake Pontchartrain--Seabrook",
        "howMany": 2,
        "sciName": "Progne subis",
        "obsValid": true,
        "locationPrivate": false,
        "obsDt": "2017-06-22 12:04",
        "obsReviewed": false,
        "comName": "Purple Martin",
        "lat": 30.0316211,
        "locID": "L727346"
    },
    {
        "lng": -90.0365832,
        "locName": "Lake Pontchartrain--Seabrook",
        "howMany": 30,
        "sciName": "Leucophaeus atricilla",
        "obsValid": true,
        "locationPrivate": false,
        "obsDt": "2017-06-22 12:04",
        "obsReviewed": false,
        "comName": "Laughing Gull",
        "lat": 30.0316211,
        "locID": "L727346"
    },
    {
        "lng": -90.0365832,
        "locName": "Lake Pontchartrain--Seabrook",
        "howMany": 1,
        "sciName": "Ardea herodias",
        "obsValid": true,
        "locationPrivate": false,
        "obsDt": "2017-06-22 12:04",
        "obsReviewed": false,
        "comName": "Great Blue Heron",
        "lat": 30.0316211,
        "locID": "L727346"
    },
    {
        "lng": -90.0365832,
        "locName": "Lake Pontchartrain--Seabrook",
        "howMany": 4,
        "sciName": "Sterna forsteri",
        "obsValid": true,
        "locationPrivate": false,
        "obsDt": "2017-06-22 12:04",
        "obsReviewed": false,
        "comName": "Forster's Tern",
        "lat": 30.0316211,
        "locID": "L727346"
    },
    {
        "lng": -90.0365832,
        "locName": "Lake Pontchartrain--Seabrook",
        "howMany": 15,
        "sciName": "Petrochelidon pyrrhonota",
        "obsValid": true,
        "locationPrivate": false,
        "obsDt": "2017-06-22 12:04",
        "obsReviewed": false,
        "comName": "Cliff Swallow",
        "lat": 30.0316211,
        "locID": "L727346"
    },
    {
        "lng": -89.9630499,
        "locName": "Audubon La Nature Center + vicinity",
        "howMany": 8,
        "sciName": "Corvus brachyrhynchos",
        "obsValid": true,
        "locationPrivate": true,
        "obsDt": "2017-06-19 06:05",
        "obsReviewed": false,
        "comName": "American Crow",
        "lat": 30.030461,
        "locID": "L444009"
    }
]